[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"
authors = ["Joey Harrison <joeyh021@icloud.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

